# Generated by Django 5.0.3 on 2024-04-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="T_DEPTS",
            fields=[
                (
                    "dept_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("dept_name", models.CharField(max_length=50)),
                ("sort_code", models.IntegerField(null=True)),
                ("dept_note", models.CharField(blank=True, max_length=255, null=True)),
                ("reg_dtm", models.DateTimeField()),
                ("upd_dtm", models.DateTimeField(blank=True, null=True)),
                ("del_dtm", models.DateTimeField(blank=True, null=True)),
                ("reg_uid", models.CharField(max_length=50)),
                ("upd_uid", models.CharField(blank=True, max_length=50, null=True)),
                ("del_uid", models.CharField(blank=True, max_length=50, null=True)),
                ("reg_name", models.CharField(max_length=50)),
                ("upd_name", models.CharField(blank=True, max_length=50, null=True)),
                ("del_name", models.CharField(blank=True, max_length=50, null=True)),
                ("reg_ip", models.CharField(blank=True, max_length=50, null=True)),
                ("upd_ip", models.CharField(blank=True, max_length=50, null=True)),
                ("del_ip", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="T_USERS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=100)),
                ("ustate", models.CharField(max_length=1)),
                ("ugbn", models.CharField(max_length=1)),
                ("dept_code", models.CharField(max_length=50)),
                ("userid", models.CharField(max_length=50)),
                ("userpw", models.CharField(max_length=255)),
                ("uemail", models.EmailField(max_length=254)),
                ("mpop_email", models.EmailField(max_length=254)),
                ("uphone", models.CharField(max_length=50)),
                ("umobile", models.CharField(max_length=50)),
                ("user_note", models.TextField(blank=True, null=True)),
                ("join_date", models.DateField(blank=True, null=True)),
                ("leav_date", models.DateField(blank=True, null=True)),
                ("vac_date", models.DateField(blank=True, null=True)),
                ("work_time_yn", models.CharField(max_length=1)),
                ("dept_amt_yn", models.CharField(max_length=1)),
                ("reg_dtm", models.DateTimeField(blank=True, null=True)),
                ("upd_dtm", models.DateTimeField(blank=True, null=True)),
                ("del_dtm", models.DateTimeField(blank=True, null=True)),
                ("reg_uid", models.CharField(blank=True, max_length=50, null=True)),
                ("upd_uid", models.CharField(blank=True, max_length=50, null=True)),
                ("del_uid", models.CharField(blank=True, max_length=50, null=True)),
                ("reg_name", models.CharField(blank=True, max_length=100, null=True)),
                ("upd_name", models.CharField(blank=True, max_length=100, null=True)),
                ("del_name", models.CharField(blank=True, max_length=100, null=True)),
                ("reg_ip", models.CharField(blank=True, max_length=50, null=True)),
                ("upd_ip", models.CharField(blank=True, max_length=50, null=True)),
                ("del_ip", models.CharField(blank=True, max_length=50, null=True)),
                ("login_dtm", models.DateTimeField(blank=True, null=True)),
                ("login_ip", models.CharField(blank=True, max_length=50, null=True)),
                ("fcm_token", models.CharField(blank=True, max_length=255, null=True)),
                ("login_mode", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "device_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "version_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("and_sdk_int", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
