# Generated by Django 5.0.3 on 2024-04-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="T_DEPTS",
        ),
        migrations.DeleteModel(
            name="T_USERS",
        ),
    ]
