# Generated by Django 5.0.3 on 2024-04-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_t_sales_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="T_TRANSFER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trns_id", models.CharField(max_length=100, null=True)),
                ("media_id", models.CharField(max_length=50, null=True)),
                ("mkt_cd", models.CharField(max_length=50, null=True)),
                ("mkt_nm", models.CharField(max_length=100, null=True)),
                ("mkt_uid", models.CharField(max_length=100, null=True)),
                ("trns_gbn", models.CharField(max_length=50, null=True)),
                ("trns_stat", models.CharField(max_length=50, null=True)),
                ("report_yn", models.CharField(max_length=10, null=True)),
                ("customer_id", models.CharField(max_length=50, null=True)),
                ("customer_nm", models.CharField(max_length=100, null=True)),
                ("trns_date", models.DateField(null=True)),
                ("req_dtm", models.DateTimeField(null=True)),
                ("app_dtm", models.DateTimeField(null=True)),
                (
                    "pre_month_amt",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("reg_gbn", models.CharField(max_length=50, null=True)),
                ("pre_mkt_cd", models.CharField(max_length=50, null=True)),
                ("trns_note", models.TextField(blank=True, null=True)),
                ("orig_gbn", models.CharField(max_length=50, null=True)),
                ("orig_date", models.DateField(null=True)),
                ("scrap_amt_dtm", models.DateTimeField(null=True)),
                ("scrap_amt_stat", models.CharField(max_length=50, null=True)),
                ("scrap_amt_try", models.IntegerField(null=True)),
                ("delete_check", models.CharField(max_length=50, null=True)),
                ("reg_dtm", models.DateTimeField(null=True)),
                ("upd_dtm", models.DateTimeField(null=True)),
                ("del_dtm", models.DateTimeField(blank=True, null=True)),
                ("reg_uid", models.CharField(max_length=50, null=True)),
                ("reg_name", models.CharField(max_length=100, null=True)),
                ("upd_uid", models.CharField(max_length=50, null=True)),
                ("upd_name", models.CharField(max_length=100, null=True)),
                ("del_uid", models.CharField(blank=True, max_length=50, null=True)),
                ("del_name", models.CharField(blank=True, max_length=100, null=True)),
                ("reg_ip", models.CharField(max_length=100, null=True)),
                ("upd_ip", models.CharField(max_length=100, null=True)),
                ("del_ip", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
