# Generated by Django 5.0.3 on 2024-04-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0006_t_transfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                (
                    "call_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("sender", models.CharField(max_length=50)),
                ("receiver", models.CharField(max_length=50)),
                ("call_date", models.DateTimeField()),
                ("call_duration", models.TimeField()),
                ("time_to_sec", models.IntegerField()),
            ],
        ),
    ]
