# Generated by Django 5.0.3 on 2024-04-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0007_callrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callrecord",
            name="call_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="callrecord",
            name="call_duration",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="callrecord",
            name="receiver",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="callrecord",
            name="sender",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="callrecord",
            name="time_to_sec",
            field=models.IntegerField(null=True),
        ),
    ]
