# Generated by Django 5.0.3 on 2024-04-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0008_alter_callrecord_call_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="T_NETSALES",
            fields=[
                (
                    "sale_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("sale_month", models.CharField(max_length=6)),
                ("mkt_name", models.CharField(max_length=100)),
                ("tot_amt", models.BigIntegerField()),
                (
                    "next_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("next_amt", models.BigIntegerField(blank=True, null=True)),
                ("target_time", models.IntegerField(blank=True, null=True)),
                ("target_call", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="CallRecord",
            new_name="T_CALL_DAY_LIST",
        ),
    ]
