from django.db import models

class T_TRANSFER(models.Model):
    trns_id = models.CharField(max_length=100, null=True)
    media_id = models.CharField(max_length=50, null=True)
    mkt_cd = models.CharField(max_length=50, null=True)
    mkt_nm = models.CharField(max_length=100, null=True)
    mkt_uid = models.CharField(max_length=100, null=True)
    trns_gbn = models.CharField(max_length=50, null=True)
    trns_stat = models.CharField(max_length=50, null=True)
    report_yn = models.CharField(max_length=10, null=True)
    customer_id = models.CharField(max_length=50, null=True)
    customer_nm = models.CharField(max_length=100, null=True)
    trns_date = models.DateField(null=True)
    req_dtm = models.DateTimeField(null=True)
    app_dtm = models.DateTimeField(null=True)
    pre_month_amt = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    reg_gbn = models.CharField(max_length=50, null=True)
    pre_mkt_cd = models.CharField(max_length=50, null=True)
    trns_note = models.TextField(blank=True, null=True)
    orig_gbn = models.CharField(max_length=50, null=True)
    orig_date = models.DateField(null=True)
    scrap_amt_dtm = models.DateTimeField(null=True)
    scrap_amt_stat = models.CharField(max_length=50, null=True)
    scrap_amt_try = models.IntegerField(null=True)
    delete_check = models.CharField(max_length=50, null=True)
    reg_dtm = models.DateTimeField(null=True)
    upd_dtm = models.DateTimeField(null=True)
    del_dtm = models.DateTimeField(null=True, blank=True)
    reg_uid = models.CharField(max_length=50, null=True)
    reg_name = models.CharField(max_length=100, null=True)
    upd_uid = models.CharField(max_length=50, null=True)
    upd_name = models.CharField(max_length=100, null=True)
    del_uid = models.CharField(max_length=50, blank=True, null=True)
    del_name = models.CharField(max_length=100, blank=True, null=True)
    reg_ip = models.CharField(max_length=100, null=True)
    upd_ip = models.CharField(max_length=100, null=True)
    del_ip = models.CharField(max_length=100, blank=True, null=True)

class T_Sales_Day(models.Model):
    sale_date = models.DateField()
    sale_date_fr = models.CharField(max_length=50, null=True)
    media_id = models.CharField(max_length=50, null=True)
    customer_id = models.CharField(max_length=50, null=True)
    customer_nm = models.CharField(max_length=100, null=True)
    mkt_cd = models.CharField(max_length=50, null=True)
    mkt_nm = models.CharField(max_length=100, null=True)
    tot_amt = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    reg_gbn = models.CharField(max_length=50, null=True)
    sale_note = models.TextField(blank=True, null=True)
    scrap_param = models.TextField(blank=True, null=True)
    reg_dtm = models.DateTimeField(null=True)
    upd_dtm = models.DateTimeField(null=True)
    reg_uid = models.CharField(max_length=50, null=True)
    reg_name = models.CharField(max_length=100, null=True)
    upd_uid = models.CharField(max_length=50, null=True)
    upd_name = models.CharField(max_length=100, null=True)
    reg_ip = models.CharField(max_length=100, null=True)
    upd_ip = models.CharField(max_length=100, null=True)

class T_USERS(models.Model):
    uid = models.CharField(max_length=50)
    username = models.CharField(max_length=100)
    ustate = models.CharField(max_length=1)
    ugbn = models.CharField(max_length=1)
    dept_code = models.CharField(max_length=50)
    userid = models.CharField(max_length=50)
    userpw = models.CharField(max_length=255)
    uemail = models.EmailField()
    mpop_email = models.EmailField()
    uphone = models.CharField(max_length=50)
    umobile = models.CharField(max_length=50)
    user_note = models.TextField(null=True, blank=True)
    join_date = models.DateField(null=True, blank=True)
    leav_date = models.DateField(null=True, blank=True)
    vac_date = models.DateField(null=True, blank=True)
    work_time_yn = models.CharField(max_length=1)
    dept_amt_yn = models.CharField(max_length=1)
    reg_dtm = models.DateTimeField(null=True, blank=True)
    upd_dtm = models.DateTimeField(null=True, blank=True)
    del_dtm = models.DateTimeField(null=True, blank=True)
    reg_uid = models.CharField(max_length=50, null=True, blank=True)
    upd_uid = models.CharField(max_length=50, null=True, blank=True)
    del_uid = models.CharField(max_length=50, null=True, blank=True)
    reg_name = models.CharField(max_length=100, null=True, blank=True)
    upd_name = models.CharField(max_length=100, null=True, blank=True)
    del_name = models.CharField(max_length=100, null=True, blank=True)
    reg_ip = models.CharField(max_length=50, null=True, blank=True)
    upd_ip = models.CharField(max_length=50, null=True, blank=True)
    del_ip = models.CharField(max_length=50, null=True, blank=True)
    login_dtm = models.DateTimeField(null=True, blank=True)
    login_ip = models.CharField(max_length=50, null=True, blank=True)
    fcm_token = models.CharField(max_length=255, null=True, blank=True)
    login_mode = models.CharField(max_length=50, null=True, blank=True)
    device_model = models.CharField(max_length=100, null=True, blank=True)
    version_code = models.CharField(max_length=50, null=True, blank=True)
    and_sdk_int = models.CharField(max_length=50, null=True, blank=True)


class T_DEPTS(models.Model):
    dept_code = models.CharField(max_length=20, primary_key=True)
    dept_name = models.CharField(max_length=50)
    sort_code = models.IntegerField(null=True)
    dept_note = models.CharField(max_length=255, null=True, blank=True)
    reg_dtm = models.DateTimeField()
    upd_dtm = models.DateTimeField(null=True, blank=True)
    del_dtm = models.DateTimeField(null=True, blank=True)
    reg_uid = models.CharField(max_length=50)
    upd_uid = models.CharField(max_length=50, null=True, blank=True)
    del_uid = models.CharField(max_length=50, null=True, blank=True)
    reg_name = models.CharField(max_length=50)
    upd_name = models.CharField(max_length=50, null=True, blank=True)
    del_name = models.CharField(max_length=50, null=True, blank=True)
    reg_ip = models.CharField(max_length=50, null=True, blank=True)
    upd_ip = models.CharField(max_length=50, null=True, blank=True)
    del_ip = models.CharField(max_length=50, null=True, blank=True)
    
class T_CALL_DAY_LIST(models.Model):
    call_id = models.CharField(max_length=100, primary_key=True)
    sender = models.CharField(max_length=50,null=True )  # send 필드는 보내는 사람을 의미하는 것으로 추정됩니다.
    receiver = models.CharField(max_length=50,null=True )  # recv 필드는 받는 사람을 의미하는 것으로 추정됩니다.
    call_date = models.DateTimeField(null=True )  # call_date 필드에는 날짜와 시간 정보가 포함되어 있습니다.
    call_duration = models.TimeField(null=True )  # call_time 필드는 통화 시간을 나타내므로 TimeField를 사용합니다.
    time_to_sec = models.IntegerField(null=True)  # timeToSec 필드는 정수 값을 가지므로 IntegerField를 사용합니다.
    
class T_NETSALES(models.Model):
    sale_id = models.CharField(max_length=50, primary_key=True)
    sale_month = models.CharField(max_length=6)  # 보통 연월은 6자리 숫자로 표현됩니다.
    mkt_name = models.CharField(max_length=100)
    tot_amt = models.BigIntegerField()  # 큰 금액을 다룰 수 있게 BigIntegerField를 사용합니다.
    next_rate = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    next_amt = models.BigIntegerField(null=True, blank=True)
    target_time = models.IntegerField(null=True, blank=True)
    target_call = models.IntegerField(null=True, blank=True)