from django.db import models

class T_TRANSFER(models.Model):
    trns_id = models.CharField(max_length=100, null=True)
    media_id = models.CharField(max_length=50, null=True)
    mkt_cd = models.CharField(max_length=50, null=True)
    mkt_nm = models.CharField(max_length=100, null=True)
    mkt_uid = models.CharField(max_length=100, null=True)
    trns_gbn = models.CharField(max_length=50, null=True)
    trns_stat = models.CharField(max_length=50, null=True)
    report_yn = models.CharField(max_length=10, null=True)
    customer_id = models.CharField(max_length=50, null=True)
    customer_nm = models.CharField(max_length=100, null=True)
    trns_date = models.DateField(null=True)
    req_dtm = models.DateTimeField(null=True)
    app_dtm = models.DateTimeField(null=True)
    pre_month_amt = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    reg_gbn = models.CharField(max_length=50, null=True)
    pre_mkt_cd = models.CharField(max_length=50, null=True)
    trns_note = models.TextField(blank=True, null=True)
    orig_gbn = models.CharField(max_length=50, null=True)
    orig_date = models.DateField(null=True)
    scrap_amt_dtm = models.DateTimeField(null=True)
    scrap_amt_stat = models.CharField(max_length=50, null=True)
    scrap_amt_try = models.IntegerField(null=True)
    delete_check = models.CharField(max_length=50, null=True)
    reg_dtm = models.DateTimeField(null=True)
    upd_dtm = models.DateTimeField(null=True)
    del_dtm = models.DateTimeField(null=True, blank=True)
    reg_uid = models.CharField(max_length=50, null=True)
    reg_name = models.CharField(max_length=100, null=True)
    upd_uid = models.CharField(max_length=50, null=True)
    upd_name = models.CharField(max_length=100, null=True)
    del_uid = models.CharField(max_length=50, blank=True, null=True)
    del_name = models.CharField(max_length=100, blank=True, null=True)
    reg_ip = models.CharField(max_length=100, null=True)
    upd_ip = models.CharField(max_length=100, null=True)
    del_ip = models.CharField(max_length=100, blank=True, null=True)

class T_Sales_Day(models.Model):
    sale_date = models.DateField()
    sale_date_fr = models.CharField(max_length=50, null=True)
    media_id = models.CharField(max_length=50, null=True)
    customer_id = models.CharField(max_length=50, null=True)
    customer_nm = models.CharField(max_length=100, null=True)
    mkt_cd = models.CharField(max_length=50, null=True)
    mkt_nm = models.CharField(max_length=100, null=True)
    tot_amt = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    reg_gbn = models.CharField(max_length=50, null=True)
    sale_note = models.TextField(blank=True, null=True)
    scrap_param = models.TextField(blank=True, null=True)
    reg_dtm = models.DateTimeField(null=True)
    upd_dtm = models.DateTimeField(null=True)
    reg_uid = models.CharField(max_length=50, null=True)
    reg_name = models.CharField(max_length=100, null=True)
    upd_uid = models.CharField(max_length=50, null=True)
    upd_name = models.CharField(max_length=100, null=True)
    reg_ip = models.CharField(max_length=100, null=True)
    upd_ip = models.CharField(max_length=100, null=True)

class T_USERS(models.Model):
    uid = models.CharField(max_length=50)
    username = models.CharField(max_length=100)
    ustate = models.CharField(max_length=1)
    ugbn = models.CharField(max_length=1)
    dept_code = models.CharField(max_length=50)
    userid = models.CharField(max_length=50)
    userpw = models.CharField(max_length=255)
    uemail = models.EmailField()
    mpop_email = models.EmailField()
    uphone = models.CharField(max_length=50)
    umobile = models.CharField(max_length=50)
    user_note = models.TextField(null=True, blank=True)
    join_date = models.DateField(null=True, blank=True)
    leav_date = models.DateField(null=True, blank=True)
    vac_date = models.DateField(null=True, blank=True)
    work_time_yn = models.CharField(max_length=1)
    dept_amt_yn = models.CharField(max_length=1)
    reg_dtm = models.DateTimeField(null=True, blank=True)
    upd_dtm = models.DateTimeField(null=True, blank=True)
    del_dtm = models.DateTimeField(null=True, blank=True)
    reg_uid = models.CharField(max_length=50, null=True, blank=True)
    upd_uid = models.CharField(max_length=50, null=True, blank=True)
    del_uid = models.CharField(max_length=50, null=True, blank=True)
    reg_name = models.CharField(max_length=100, null=True, blank=True)
    upd_name = models.CharField(max_length=100, null=True, blank=True)
    del_name = models.CharField(max_length=100, null=True, blank=True)
    reg_ip = models.CharField(max_length=50, null=True, blank=True)
    upd_ip = models.CharField(max_length=50, null=True, blank=True)
    del_ip = models.CharField(max_length=50, null=True, blank=True)
    login_dtm = models.DateTimeField(null=True, blank=True)
    login_ip = models.CharField(max_length=50, null=True, blank=True)
    fcm_token = models.CharField(max_length=255, null=True, blank=True)
    login_mode = models.CharField(max_length=50, null=True, blank=True)
    device_model = models.CharField(max_length=100, null=True, blank=True)
    version_code = models.CharField(max_length=50, null=True, blank=True)
    and_sdk_int = models.CharField(max_length=50, null=True, blank=True)


class T_DEPTS(models.Model):
    dept_code = models.CharField(max_length=20, primary_key=True)
    dept_name = models.CharField(max_length=50)
    sort_code = models.IntegerField(null=True)
    dept_note = models.CharField(max_length=255, null=True, blank=True)
    reg_dtm = models.DateTimeField()
    upd_dtm = models.DateTimeField(null=True, blank=True)
    del_dtm = models.DateTimeField(null=True, blank=True)
    reg_uid = models.CharField(max_length=50)
    upd_uid = models.CharField(max_length=50, null=True, blank=True)
    del_uid = models.CharField(max_length=50, null=True, blank=True)
    reg_name = models.CharField(max_length=50)
    upd_name = models.CharField(max_length=50, null=True, blank=True)
    del_name = models.CharField(max_length=50, null=True, blank=True)
    reg_ip = models.CharField(max_length=50, null=True, blank=True)
    upd_ip = models.CharField(max_length=50, null=True, blank=True)
    del_ip = models.CharField(max_length=50, null=True, blank=True)